// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'hello_feign_client.dart' as prefix1;
import 'package:fengwuxp_dart_openfeign/src/annotations/feign_client.dart'
    as prefix0;
import 'package:fengwuxp_dart_openfeign/src/annotations/path_variable.dart'
    as prefix7;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_body.dart'
    as prefix8;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_header.dart'
    as prefix5;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_mapping.dart'
    as prefix2;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_param.dart'
    as prefix6;
import 'package:fengwuxp_dart_openfeign/src/annotations/signature.dart'
    as prefix4;
import 'package:fengwuxp_dart_openfeign/src/constant/authentication_type.dart'
    as prefix3;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.DartFeignClient(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'HelloFeignClient',
            r'.HelloFeignClient',
            7,
            0,
            const prefix0.DartFeignClient(),
            const <int>[0, 1, 2, 3, 4, 5],
            const <int>[6, 7, 8, 9, 10, 11, 0, 1],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.Feign,
              const prefix0.FeignClient(name: "hello_client", value: "/")
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(
            r'getHello',
            4325378,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[0, 1, 2],
            const prefix0.DartFeignClient(),
            const <Object>[
              const prefix2.GetMapping(
                  value: "/",
                  authenticationType: prefix3.AuthenticationType.NONE)
            ]),
        r.MethodMirrorImpl(
            r'getTest',
            4325378,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[3, 4, 5],
            const prefix0.DartFeignClient(),
            const <Object>[const prefix2.GetMapping(value: "/test")]),
        r.MethodMirrorImpl(
            r'getHelloForObject',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[6, 7, 8],
            const prefix0.DartFeignClient(),
            const <Object>[const prefix2.GetMapping(value: "/get_hello")]),
        r.MethodMirrorImpl(
            r'queryHello',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[9, 10],
            const prefix0.DartFeignClient(),
            const <Object>[
              const prefix2.GetMapping(value: "/get_hello"),
              const prefix4.Signature(const ["id"])
            ]),
        r.MethodMirrorImpl(
            r'findHelloById',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[11, 12],
            const prefix0.DartFeignClient(),
            const <Object>[const prefix2.GetMapping(value: "/get_hello/{id}")]),
        r.MethodMirrorImpl(
            r'putDataTest',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[13, 14],
            const prefix0.DartFeignClient(),
            const <Object>[const prefix2.PutMapping(value: "/put_data_test")]),
        r.MethodMirrorImpl(r'==', 131074, null, -1, -1, -1, null,
            const <int>[15], const prefix0.DartFeignClient(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.DartFeignClient(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            4325378,
            null,
            -1,
            -1,
            -1,
            null,
            const <int>[16],
            const prefix0.DartFeignClient(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.DartFeignClient(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.DartFeignClient(), const []),
        r.MethodMirrorImpl(
            r'delegateInvoke',
            4325378,
            null,
            -1,
            -1,
            -1,
            null,
            const <int>[17, 18, 19, 20],
            const prefix0.DartFeignClient(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'name',
            32774,
            0,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix5.RequestHeader()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            32774,
            0,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix6.RequestParam()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            0,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'name',
            32774,
            1,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix5.RequestHeader()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            2129926,
            1,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix6.RequestParam()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            1,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'name',
            32774,
            2,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix5.RequestHeader()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            32774,
            2,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix6.RequestParam()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            2,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'req', 32774, 3, const prefix0.DartFeignClient(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            3,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            32774,
            4,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix7.PathVariable()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            4,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'req',
            32774,
            5,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix8.RequestBody()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            36870,
            5,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            6,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            8,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'methodName',
            32774,
            11,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'positionalArguments',
            2129926,
            11,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            45062,
            11,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #feignOptions),
        r.ParameterMirrorImpl(
            r'serializer',
            2142214,
            11,
            const prefix0.DartFeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #serializer)
      ],
      <Type>[prefix1.HelloFeignClient],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'delegateInvoke': (dynamic instance) => instance.delegateInvoke,
        r'getHello': (dynamic instance) => instance.getHello,
        r'getTest': (dynamic instance) => instance.getTest
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
