// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'hello_feign_client.dart' as prefix1;
import 'mock_feign_configuration.dart' as prefix2;
import 'package:fengwuxp_dart_openfeign/src/annotations/feign_client.dart'
    as prefix0;
import 'package:fengwuxp_dart_openfeign/src/annotations/query_param.dart'
    as prefix5;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_header.dart'
    as prefix4;
import 'package:fengwuxp_dart_openfeign/src/annotations/request_mapping.dart'
    as prefix3;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FeignClient(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'HelloFeignClient',
            r'.HelloFeignClient',
            7,
            0,
            const prefix0.FeignClient(),
            const <int>[0, 1, 2, 3],
            const <int>[4, 5, 6, 7, 8, 9, 0],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => () => b ? prefix1.HelloFeignClient() : null},
            -1,
            0,
            const <int>[],
            const <Object>[
              const prefix0.FeignClient(
                  name: "hello_client",
                  value: "hello",
                  configuration: const prefix2.MockFeignConfiguration())
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(
            r'getHello',
            4325378,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[0, 1, 2],
            const prefix0.FeignClient(),
            const <Object>[const prefix3.GetMapping(value: "/get_hello")]),
        r.MethodMirrorImpl(
            r'getHelloForObject',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[3, 4, 5],
            const prefix0.FeignClient(),
            const <Object>[const prefix3.GetMapping(value: "/get_hello")]),
        r.MethodMirrorImpl(
            r'queryHello',
            4325890,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[6, 7],
            const prefix0.FeignClient(),
            const <Object>[const prefix3.GetMapping(value: "/get_hello")]),
        r.MethodMirrorImpl(r'', 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.FeignClient(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, -1, -1, null,
            const <int>[8], const prefix0.FeignClient(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.FeignClient(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            4325378,
            null,
            -1,
            -1,
            -1,
            null,
            const <int>[9],
            const prefix0.FeignClient(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.FeignClient(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.FeignClient(), const []),
        r.MethodMirrorImpl(r'delegateInvoke', 4325378, null, -1, -1, -1, null,
            const <int>[10, 11, 12, 13], const prefix0.FeignClient(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'name',
            32774,
            0,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix4.RequestHeader()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            32774,
            0,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix5.QueryParam()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            45062,
            0,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #feignOptions),
        r.ParameterMirrorImpl(
            r'name',
            32774,
            1,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix4.RequestHeader()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            32774,
            1,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix5.QueryParam()],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            45062,
            1,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #feignOptions),
        r.ParameterMirrorImpl(r'req', 32774, 2, const prefix0.FeignClient(), -1,
            -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            45062,
            2,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #feignOptions),
        r.ParameterMirrorImpl(r'other', 16390, 4, const prefix0.FeignClient(),
            null, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            6,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'methodName',
            32774,
            9,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'positionalArguments',
            2129926,
            9,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'feignOptions',
            45062,
            9,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #feignOptions),
        r.ParameterMirrorImpl(
            r'serializer',
            2142214,
            9,
            const prefix0.FeignClient(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #serializer)
      ],
      <Type>[prefix1.HelloFeignClient],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'delegateInvoke': (dynamic instance) => instance.delegateInvoke,
        r'getHello': (dynamic instance) => instance.getHello
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
